In [1]:
import pandas as pd

In [2]:
import zipfile
import os
import requests
import pathlib
from pathlib import Path

In [3]:
# import requests, zipfile, Path from pathlib

# Setup path to a data folder
csv_path = Path("D:\Coding\Dev Weekend\AI Engineering\Pandas\data")

# if the image folder doesn's exist, download it and prepare it
if csv_path.is_dir():
  print(f"{csv_path} already exists, skipping download...")
else:
  print(f"{csv_path} does not exist, creating one...")
  csv_path.mkdir(parents = True, exist_ok = True)

# Download pizza, steak and sushi data
with open(csv_path / "nyc_weather.csv", "wb") as f:
  request = requests.get("https://raw.githubusercontent.com/codebasics/py/refs/heads/master/pandas/1_intro/nyc_weather.csv")
  print("Downloading weather data...")
  f.write(request.content)
  print("Weather data downloaded...")

# # Unzip pizza, steam, sushi data
# with zipfile.ZipFile(csv_path / "nyc_weather.zip", "r") as zip_ref:
#   print("Unzipping weather data...")
#   zip_ref.extractall(csv_path)

D:\Coding\Dev Weekend\AI Engineering\Pandas\data already exists, skipping download...
Downloading weather data...
Weather data downloaded...

In [4]:
df = pd.read_csv(csv_path / "nyc_weather.csv")

In [5]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [6]:
df['Temperature'].max()

np.int64(50)

In [7]:
df['EST'][df['Events'] == 'Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [8]:
df.fillna(0, inplace = True)
df['WindSpeedMPH'].mean()

np.float64(6.225806451612903)

In [9]:
# import requests, zipfile, Path from pathlib

# Setup path to a data folder
csv_path = Path("D:\Coding\Dev Weekend\AI Engineering\Pandas\data")

# if the image folder doesn's exist, download it and prepare it
if csv_path.is_dir():
  print(f"{csv_path} already exists, skipping download...")
else:
  print(f"{csv_path} does not exist, creating one...")
  csv_path.mkdir(parents = True, exist_ok = True)

# Download pizza, steak and sushi data
with open(csv_path / "weather_data.csv", "wb") as f:
  request = requests.get("https://raw.githubusercontent.com/codebasics/py/3ee4bde332ae7a10499c2679900094fa22ae191f/pandas/2_dataframe_basics/weather_data.csv")
  print("Downloading weather data...")
  f.write(request.content)
  print("Weather data downloaded...")

# # Unzip pizza, steam, sushi data
# with zipfile.ZipFile(csv_path / "nyc_weather.zip", "r") as zip_ref:
#   print("Unzipping weather data...")
#   zip_ref.extractall(csv_path)

D:\Coding\Dev Weekend\AI Engineering\Pandas\data already exists, skipping download...
Downloading weather data...
Weather data downloaded...

In [10]:
df = pd.read_csv("D:\Coding\Dev Weekend\AI Engineering\Pandas\data\weather_data.csv")
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

We can create DataFrame from a normal data too

In [11]:
weather_data = pd.DataFrame({
    'day': ['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'],
    'temperature': [32, 35, 28, 24, 32, 31],
    'windspeed': [6, 7, 2, 7, 4, 2],
    'event': ['Rain', 'Sunny', 'Snow', 'Snow', 'Rain', 'Sunny']
})
weather_data

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [12]:
df.shape

(6, 4)

In [13]:
rows, columns = df.shape
rows, columns

(6, 4)

In [14]:
df.tail()

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [15]:
df[2:5]

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [16]:
df[:]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [17]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [18]:
df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [19]:
df['day']

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [20]:
type(df['event'])

pandas.core.series.Series

In [21]:
df[['event', 'day']]

   event       day
0   Rain  1/1/2017
1  Sunny  1/2/2017
2   Snow  1/3/2017
3   Snow  1/4/2017
4   Rain  1/5/2017
5  Sunny  1/6/2017

In [22]:
df.info

<bound method DataFrame.info of         day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny>

In [23]:
df['temperature'].max()

np.int64(35)

In [24]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [25]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [26]:
df[df.temperature >= 32]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain

In [27]:
df[df.temperature == df.temperature.max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [28]:
df[['day', 'temperature']][df.temperature == df['temperature'].max()]

        day  temperature
1  1/2/2017           35

In [29]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [30]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [31]:
df.set_index('day', inplace = True)

In [32]:
df.loc['1/4/2017']

temperature      24
windspeed         7
event          Snow
Name: 1/4/2017, dtype: object

In [33]:
df.reset_index(inplace = True)

In [34]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [35]:
df.set_index('event', inplace = True)

In [36]:
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [37]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7

In [38]:
df.reset_index(inplace = True)

In [39]:
df

   event       day  temperature  windspeed
0   Rain  1/1/2017           32          6
1  Sunny  1/2/2017           35          7
2   Snow  1/3/2017           28          2
3   Snow  1/4/2017           24          7
4   Rain  1/5/2017           32          4
5  Sunny  1/6/2017           31          2

In [57]:
df.iloc[[0, 2]]

        day  temperature  windspeed event
0  1/1/2017           32          6  Rain
2  1/3/2017           28          2  Snow

In [58]:
df.loc['day']

KeyError: 'day'

In [41]:
df.drop(index = 3, inplace = True)
df

   event       day  temperature  windspeed
0   Rain  1/1/2017           32          6
1  Sunny  1/2/2017           35          7
2   Snow  1/3/2017           28          2
4   Rain  1/5/2017           32          4
5  Sunny  1/6/2017           31          2

In [42]:
df.drop(index = (df.index[3:]), inplace = True)
df

   event       day  temperature  windspeed
0   Rain  1/1/2017           32          6
1  Sunny  1/2/2017           35          7
2   Snow  1/3/2017           28          2

In [43]:
df

   event       day  temperature  windspeed
0   Rain  1/1/2017           32          6
1  Sunny  1/2/2017           35          7
2   Snow  1/3/2017           28          2

### How to create DataFrames using different ways

In [44]:
df = pd.read_excel("D:\Coding\Dev Weekend\AI Engineering\Pandas\data\weather_data.xlsx")
df

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [45]:
weather_data = {
    'day': ['1/1/2017', '1/2/2017', '1/3/2017'],
    'temperature': [32, 35, 28],
    'windspeed': [6, 7, 2],
    'event': ['Rain', 'Sunny', 'Snow']
}
df = pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [46]:
weather_data = [
    ('1/1/2017', 32, 6, 'Rain'),
    ('1/2/2017', 35, 7, 'Sunny'),
    ('1/3/2017', 28, 2, 'Snow')
]

df = pd.DataFrame(weather_data, columns = ['day', 'temperature', 'windspeed', 'event'])
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [47]:
weather_data = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'}
]
df = pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow